### ISSUE TITLE
Generated content includes redundant files and directories

### ISSUE THREAD

**Issue by 9ao9ai9ar** [mhdadk/stack-exchange-backup#1]
Although the [Format](https://github.com/mhdadk/stack-exchange-backup?tab=readme-ov-file#format) section reads (emphasis mine):

> If the Markdown file represents a question, then the question creator will be you. Otherwise, ***if the Markdown file represents an answer, the question creator will not be you, but the creator of one of the answers included in the Markdown file will be you***.

the [Logic](https://github.com/mhdadk/stack-exchange-backup?tab=readme-ov-file#logic) section contradicts this and dictates the actual behavior of the script, which generates the answer Markdown files even if the questions associated with the answers are also created by the user and the efforts have already been duplicated in step 3(c).

For the Stack Exchange subsites where the user has not created any content in, the site folders and the questions and answers subfolders within are created albeit empty. These empty folders serve no purpose whatsoever and only distract the user.

I propose that the duplicate answer files and the empty folders not be created by default.

**Comment by mhdadk** [comment]
Thank you for the comment!

Unfortunately, I don’t have the bandwidth at the moment to work on this. Feel free to submit a PR on this and I would be happy to review.

**Comment by 9ao9ai9ar** [comment]
In the process of understanding the source code and the Stack Exchange API, I am essentially rewriting the script while keeping its logic and dependencies, so I hope you won't mind a haphazard PR. I'm also on limited bandwidth at the moment, so I expect to be able to submit a PR in two weeks time at the earliest.

**Comment by mhdadk** [comment]
@9ao9ai9ar If the rewrite is indeed major, then I would suggest you fork this repository instead and make your changes there. I would be happy to edit the README in this repo to point to your fork as an alternative.

**Comment by 9ao9ai9ar** [comment]
@mhdadk Sorry, it's taking longer than expected: I have a bit of catching up to do after 5 years of break from programming Python, and there are some problems I've found and preliminary work that needs to be done regarding the Stack Exchange API. I will fork this repository, but still plan to [submit a PR from my fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) for you to review the changes. I'll proceed to close this issue to avoid duplicate work, and because it can trivially be solved with two lines of Bash.

For the record, the two lines of Bash are as follows:

```bash
# Delete redundant (empty) directories
find q_and_a -type d -empty -delete
# Delete redundant files
find q_and_a -type f -exec sha1sum -t {} + |
    sort |
    uniq -w 40 --repeated |
    awk -F'[ *]' '{ print $NF; }' |
    xargs -rp rm
```
