### ISSUE TITLE
Provide a way to retrieve questions and answers that have been deleted

### ISSUE THREAD

**Issue by 9ao9ai9ar** [mhdadk/stack-exchange-backup#2]
Tracking the same [feature request](https://stackapps.com/q/1917) on Stack Apps. The official [Stack Exchange API](https://api.stackexchange.com/), as of today at `v2.3`, does not provide a way to fetch deleted posts.

**Comment by mhdadk** [comment]
My code depends on the Stack API, so if it can’t do it, I surely can’t.

**Comment by 9ao9ai9ar** [comment]
I am well aware of that, just pointing it out for the more casual users who may not follow the Stack Exchange API development closely. I also don't expect this to change in the future, but a note in the README would quell any misunderstanding and point out that this feature rests on Stack Exchange's side, and in particular, the Stack Exchange API is the blocking issue.
